tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

  - name: Setup dotnet
    before: |
      # Install dependencies
      sudo apt-get update
      sudo apt-get install -y wget

      # Download and install .NET SDK
      wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      chmod +x dotnet-install.sh
      ./dotnet-install.sh --channel 8.0

      # Export environment variables
      echo 'export DOTNET_ROOT=$HOME/.dotnet' >> ~/.bashrc
      echo 'export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools' >> ~/.bashrc
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools

    init: |
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools
  - name: set-aws-env
      echo 'export AWS_ACCESS_KEY_ID=your-access-key' >> ~/.bashrc
      echo 'export AWS_SECRET_ACCESS_KEY=your-secret-key' >> ~/.bashrc
      echo 'export AWS_REGION=us-east-1' >> ~/.bashrc
      export AWS_ACCESS_KEY_ID=your-access-key
      export AWS_SECRET_ACCESS_KEY=your-secret-key
      export AWS_REGION=us-east-1
