# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - name: aws-cli-setup
    init: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
    command: |
      aws --version
      echo "AWS CLI is ready"

# Set AWS_CLI_AUTO_PROMPT globally
env:
  AWS_CLI_AUTO_PROMPT: on-partial
